components:
  parameters:
    page:
      description: Page to retrieve from the entire result set
      in: query
      name: page
      schema:
        default: 1
        minimum: 1
        type: integer
    page[number]:
      description: Page to retrieve from the entire result set
      in: query
      name: page[number]
      schema:
        default: 1
        minimum: 1
        type: integer
    page[size]:
      description: Max amount of objects to return per page in the response
      in: query
      name: page[size]
      schema:
        default: 100
        maximum: 100
        type: integer
    page_size:
      description: Max amount of objects to return per page in the response
      in: query
      name: page_size
      schema:
        default: 100
        maximum: 100
        type: integer
    q:
      description: Apply search to query
      in: query
      name: q
      schema:
        type: string
  responses:
    BadRequestError:
      description: Invalid request sent to endpoint
    ForbiddenError:
      description: Invalid permissions to perform operation
    NotFoundError:
      description: The specified resource was not found
    UnauthorizedError:
      description: Access token is missing or invalid
    UnprocessableEntityError:
      description: Unable to process the contained instructions
  schemas:
    Attribute:
      properties:
        attribute_id:
          type: integer
        value:
          type: string
      required:
      - attribute_id
      - value
      type: object
    CablePath:
      properties:
        a_side: {}
        id:
          type: string
        type:
          type: string
        z_side: {}
      required:
      - a_side
      - id
      - z_side
      type: object
    EPAccessory:
      properties:
        created_at:
          readOnly: true
        description:
          type: string
        id:
          readOnly: true
          type: integer
        labor_hours:
          default: !!python/object/apply:decimal.Decimal
          - 0E-10
          type:
          - number
          - '''null'''
        manufacturer:
          default: ''
          type: string
        model:
          default: ''
          type: string
        price:
          default: !!python/object/apply:decimal.Decimal
          - 0E-10
          type:
          - number
          - '''null'''
      required:
      - description
      type: object
    EPContent:
      properties:
        attribute:
          default: []
          items:
            $ref: '#/components/schemas/Attribute'
          type: array
        child:
          default: []
          items:
            $ref: '#/components/schemas/SubElement'
          type: array
        pdf_url:
          default: []
          items:
            $ref: '#/components/schemas/Link'
          maxItems: 2
          type: array
      type: object
    ElementProfileSchema:
      properties:
        accessories:
          items:
            $ref: '#/components/schemas/EPAccessory'
          type: array
        content:
          $ref: '#/components/schemas/EPContent'
        created_at:
          readOnly: true
        created_by:
          readOnly: true
          type: integer
        element_id:
          type: integer
        id:
          readOnly: true
          type: integer
        is_default:
          type: boolean
        modified_at:
          readOnly: true
        name:
          type: string
        sort:
          type: integer
        team_id:
          type: integer
      required:
      - content
      - element_id
      - name
      - team_id
      type: object
    FolderSchema:
      properties:
        id:
          readOnly: true
          type: string
        label:
          type: string
        name:
          type: string
        site_external_id:
          type: string
          writeOnly: true
        site_id:
          readOnly: true
          type: integer
        team_id:
          type: integer
      required:
      - name
      type: object
    Link:
      properties:
        link_type:
          type: integer
        name:
          type: string
        url:
          format: url
          type: string
      required:
      - link_type
      - name
      - url
      type: object
    PathConnection:
      properties:
        end: {}
        start: {}
      type: object
    RelatedUser:
      properties:
        first_name:
          type: string
        last_name:
          type: string
        user_id: {}
      type: object
    ShareSiteOrSurveyRequestSchema:
      properties:
        created_at:
          readOnly: true
          type:
          - '''null'''
        emails:
          items:
            format: email
            type: string
          type: array
        expiration_date: {}
        message:
          type: string
        modified_at:
          readOnly: true
          type:
          - '''null'''
      required:
      - emails
      - expiration_date
      type: object
    SiteSchema:
      properties:
        city:
          maxLength: 250
          type: string
        created_at:
          readOnly: true
          type:
          - '''null'''
        creator:
          allOf:
          - $ref: '#/components/schemas/UserResponse'
          readOnly: true
        is_archived: {}
        label:
          maxLength: 255
          type: string
        legacy_site_id:
          readOnly: true
          type: integer
        modified_at:
          readOnly: true
          type:
          - '''null'''
        modifier:
          allOf:
          - $ref: '#/components/schemas/UserResponse'
          readOnly: true
        name:
          maxLength: 250
          type: string
        reference_id:
          maxLength: 255
          type: string
        site_id:
          type: string
        state:
          maxLength: 250
          type: string
        street:
          maxLength: 250
          type: string
        tags:
          items:
            type: string
          type: array
        team_id:
          type: integer
        version:
          readOnly: true
          type: integer
        zip_code:
          maxLength: 250
          type: string
      required:
      - name
      - team_id
      type: object
    SubElement:
      properties:
        element_id:
          type: string
        systemtype_id:
          type: string
      required:
      - element_id
      - systemtype_id
      type: object
    SurveyAnnotation:
      properties:
        category: {}
        end_point: {}
        font_size:
          type: string
        id:
          readOnly: true
          type: string
        location: {}
        size:
          type: string
        start_point: {}
        stroke_color:
          type: string
        stroke_width:
          type: string
        text:
          type: string
      required:
      - category
      - location
      - stroke_color
      - stroke_width
      type: object
    SurveyAttribute:
      properties:
        attribute_id:
          type: integer
        id:
          readOnly: true
          type: integer
        name:
          type: string
        value:
          type: string
      required:
      - attribute_id
      - name
      - value
      type: object
    SurveyElement:
      properties:
        id:
          type: string
        name:
          type: string
        element_id:
          type: integer
        element_index:
          type: integer
        element_profile_id:
          type: integer
        systemtype_id:
          type: integer
        variant: {}
        z_order:
          type: integer
        position: {}
        photo_urls:
          items:
            type: string
          type: array
        pdf_urls:
          items:
            type: object
          type: array
        attributes:
          items:
            $ref: '#/components/schemas/SurveyAttribute'
          type: array
        accessories:
          items:
            $ref: '#/components/schemas/SurveyElementAccessory'
          type: array
        children:
          items:
            $ref: '#/components/schemas/SurveyElement'
          type: array
        cables:
          items:
            $ref: '#/components/schemas/CablePath'
          type: array
        connections:
          $ref: '#/components/schemas/PathConnection'
        activity_log:
          items:
            $ref: '#/components/schemas/SurveyElementActivityLog'
          type: array
      required:
      - element_id
      - id
      - name
      - position
      - systemtype_id
      type: object
    SurveyElementAccessory:
      properties:
        description:
          type: string
        id:
          readOnly: true
          type: string
        labor_hours:
          type: number
        manufacturer:
          type: string
        model:
          type: string
        price: {}
        quantity: {}
        row_index:
          type: integer
      required:
      - manufacturer
      - model
      - row_index
      type: object
    SurveyElementActivityLog:
      properties:
        date:
          readOnly: true
        entry:
          type: string
        id:
          readOnly: true
          type: string
      type: object
    SurveyFields:
      properties:
        field_id:
          type: string
        value:
          type: string
      required:
      - field_id
      - value
      type: object
    SurveyOptions:
      properties:
        id:
          type: string
        inputs:
          items:
            $ref: '#/components/schemas/SurveyFields'
          type: array
        scope:
          enum:
          - template
          - model
          - content
          type: string
        template_name:
          type: string
        value:
          type: boolean
      required:
      - id
      - scope
      - value
      type: object
    SurveyReportRequestSchema:
      properties:
        custom_data:
          type: object
        filters:
          items:
            type: object
          type: array
        is_excel:
          default: false
          type: boolean
        is_site_report:
          default: false
          type: boolean
        name:
          type: string
        options:
          items:
            $ref: '#/components/schemas/SurveyOptions'
          type: array
        output:
          enum:
          - pdf
          - html
          - xls
          type: string
        paper_size:
          type: string
        report_id:
          format: uuid
          type: string
        site_id:
          type: string
        survey_ids:
          items:
            type: string
          type: array
      required:
      - name
      - output
      - report_id
      - site_id
      type: object
    SurveyReportRequestSchemaDeprecated:
      properties:
        custom_data:
          type: object
        filters:
          items:
            type: object
          type: array
        ids:
          items:
            type: string
          type: array
        is_excel:
          default: false
          type: boolean
        is_site_report:
          default: false
          type: boolean
        name:
          type: string
        options:
          items:
            $ref: '#/components/schemas/SurveyOptions'
          type: array
        output:
          enum:
          - pdf
          - html
          - xls
          type: string
        paper_size:
          type: string
        report_id:
          format: uuid
          type: string
        site_id:
          type: string
      required:
      - name
      - output
      - report_id
      - site_id
      type: object
    SurveySchema:
      properties:
        id:
          readOnly: true
          type: string
        title:
          type: string
        label:
          type: string
        reference_id:
          type: string
        description:
          type: string
        summary:
          type: string
        location:
          type: string
        status:
          writeOnly: true
        site:
          readOnly: true
        icon_size:
          type: integer
        is_archived:
          readOnly: true
          type: boolean
        unit: {}
        version:
          readOnly: true
          type: integer
        margin_range:
          type: number
        type:
          readOnly: true
        floorplan_scale:
          type: number
        preview_image:
          readOnly: true
          type: string
        floorplan_url:
          readOnly: true
          type: string
        creator:
          readOnly: true
          type: integer
        editor:
          allOf:
          - $ref: '#/components/schemas/RelatedUser'
          readOnly: true
        modifier:
          readOnly: true
          type: integer
        created_at:
          readOnly: true
        modified_at:
          readOnly: true
        elements:
          items:
            $ref: '#/components/schemas/SurveyElement'
          type: array
        annotations:
          items:
            $ref: '#/components/schemas/SurveyAnnotation'
          type: array
        users:
          readOnly: true
      required:
      - icon_size
      - margin_range
      - title
      - unit
      type: object
    UserResponse:
      properties:
        first_name:
          type: string
        last_name:
          type: string
        user_id:
          type: integer
      required:
      - user_id
      type: object
  securitySchemes:
    jwt:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  title: System Surveyor API
  version: 2.0.0
openapi: 3.1.0
paths:
  /v3/resource:
    get:
      description: 'Resource path is a relative URL to the binary resource in EFS,
        passed in a `path` query parameter.


        Example path: `2022/08/05/207e7214-6792-4288-8820-438b1f3233be.png`

        '
      operationId: get_resource
      parameters:
      - description: Relative URL of the resource
        in: path
        name: path
        required: true
        schema:
          example: 2022/08/05/207e7214-6792-4288-8820-438b1f3233be.png
          type: string
      public: true
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: A binary resource file
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      summary: Fetches a binary resource and returns it as bytes.
      tags:
      - Resources
      - v3
  /v3/survey_element/{survey_element_id}/resource:
    post:
      operationId: add_survey_element_resource
      parameters:
      - description: The external id of the surveyelement
        in: path
        name: survey_element_id
        required: true
      public: true
      requestBody:
        content:
          application/pdf:
            schema:
              example: /tmp/path-to-file.pdf
              format: binary
              type: string
          image/jpeg:
            schema:
              example: /tmp/path-to-file.jpeg
              format: binary
              type: string
          image/jpg:
            schema:
              example: /tmp/path-to-file.jpg
              format: binary
              type: string
          image/png:
            schema:
              example: /tmp/path-to-file.png
              format: binary
              type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    properties:
                      resource_url:
                        example: 2022/11/01/39dace0d-7aa3-47c7-9bff-9c87fbe2c00b.png
                        type: string
                    type: object
                type: object
          description: The path to the uploaded file
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      summary: Sets an image to a survey element.
      tags:
      - Resources
      - v3

