openapi: 3.1.0

info:
  title: System Surveyor Public API
  version: 2.0.0

paths:
  /v2/site:
    post:
      summary: Create a new site
      operationId: createSite
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestSite"
      responses:
        "201":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  site_id:
                    type: string

  /v2/site/{id}:
    parameters:
      - name: id
        in: path
        description: Site ID
        required: true
        schema:
          type: integer

    get:
      summary: Get site information
      description: Response also includes available permissions for the current user of the site
      operationId: getSiteById
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  site_id:
                    type: string
                  team_id:
                    type: number
                  name:
                    type: string
                  label:
                    type: string
                  city:
                    type: string
                  state:
                    type: string
                  street:
                    type: string
                  zip_code:
                    type: string
                  creator:
                    type: object
                    properties:
                      user_id:
                        type: number

                      first_name:
                        type: string

                      last_name:
                        type: string
                  modifier:
                    type: object
                    properties:
                      user_id:
                        type: number
                      first_name:
                        type: string
                      last_name:
                        type: string
                  is_archived:
                    type: boolean
                  version:
                    type: number
                  reference_id:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string

    put:
      summary: Update a site
      description: Only team members, guests with edit permissions, site creators, account admins and team admins can update sites.
      operationId: updateSite
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestSite"
      responses:
        "200":
          description: "OK"


components:
  schemas:
    requestSite:
      type: object
      properties:
        name:
          type: string
        team_id:
          type: integer
        state:
          type: string
        city:
          type: string
        zip_code:
          type: string
        street:
          type: string
        label:
          type: string
        version:
          type: integer
        reference_id:
          type: string
        tags:
          type: array
          items:
            type: string
