name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ruby-version: 3.2

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Widdershins
      run: sudo npm install -g widdershins

    - uses: actions/checkout@v3

    - name: Generate Markdown
      run: widdershins --search false --language_tabs 'shell:cURL' 'python:Python' 'csharp:C#' --summary --expandBody docs.yaml -o source/index.html.md

    - name: Modify Markdown (custom text sections)
      run: python custom_swagger.py

    - name: Commit to Repository
      uses: EndBug/add-and-commit@v9
      with:
        add: source/index.html.md
        default_author: github_actions
        message: "Source Index Update"

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.ruby-version }}

    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          gems-${{ runner.os }}-${{ matrix.ruby-version }}-
          gems-${{ runner.os }}-

    - run: bundle config set deployment 'true'
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - run: bundle exec middleman build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
